"""
Slack delivery: posts the dev team report to a Slack channel
via an incoming webhook. No bot token required.
"""

import os
import logging
import requests

log = logging.getLogger(__name__)

SLACK_MAX_CHARS = 3000  # Slack block text limit


def _chunk(text, size=SLACK_MAX_CHARS):
    """Split text into chunks that fit within Slack block limits."""
    lines = text.split("\n")
    chunks, current = [], []
    length = 0
    for line in lines:
        if length + len(line) + 1 > size:
            chunks.append("\n".join(current))
            current, length = [], 0
        current.append(line)
        length += len(line) + 1
    if current:
        chunks.append("\n".join(current))
    return chunks


def _build_blocks(report, date_str):
    """Convert markdown report into Slack block kit blocks."""
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f":bar_chart: Dev Team Product Report — {date_str}",
            },
        },
        {"type": "divider"},
    ]

    for chunk in _chunk(report):
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": chunk},
        })

    blocks.append({"type": "divider"})
    blocks.append({
        "type": "context",
        "elements": [{
            "type": "mrkdwn",
            "text": "_Generated by market-intel-digest · Claude Opus 4.6_",
        }],
    })
    return blocks


def send(report, date_str=None, webhook_url=None):
    """
    Post the dev team report to Slack via incoming webhook.
    webhook_url falls back to SLACK_WEBHOOK_URL env var.
    """
    webhook_url = webhook_url or os.getenv("SLACK_WEBHOOK_URL")
    if not webhook_url:
        log.error("SLACK_WEBHOOK_URL not set — skipping Slack delivery")
        return False

    if not date_str:
        from datetime import datetime
        date_str = datetime.now().strftime("%Y-%m-%d")

    blocks = _build_blocks(report, date_str)

    try:
        resp = requests.post(
            webhook_url,
            json={"blocks": blocks},
            timeout=10,
        )
        resp.raise_for_status()
        log.info("Dev report delivered to Slack.")
        return True
    except Exception as e:
        log.error(f"Slack delivery failed: {e}")
        return False
